language: scala

scala:
   - 2.12.6
   
python:
  - "2.7"

jobs:
  include:
    - stage: verify

      before_script:
        - sbt stage

      script:
        - sbt ++$TRAVIS_SCALA_VERSION test
        - ./build.sh
